- name: Cache
  uses: actions/cache@v5.1.0
  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
    restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    enableCrossOsArchive: # optional, default is false
    # Fail the workflow if cache entry is not found
    fail-on-cache-miss: # optional, default is false
    # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    lookup-only: # optional, default is false
    # Run the post step to save the cache even if another step before fails
    save-always: # optional, default is false\


- name: Multi-output Example Action
  # You may pin to the exact commit or the version.
  # uses: Ompragash/maths-action@ce21f97ec3f77908d100f117062df204d5cd2555
  uses: Ompragash/maths-action@v1.0.0
  with:
    # First input value
    input1: # default is 10
    # Second input value
    input2: # default is 20


- name: Image Actions
  # You may pin to the exact commit or the version.
  # uses: calibreapp/image-actions@9d037c06280028c110ff61c433ad4dc7d33c3c43
  uses: calibreapp/image-actions@1.5.0
  with:
    # The token that the action will use to create and update the pull request.
    GITHUB_TOKEN: # optional, default is ${{ github.token }}
    # JPEG quality level
    jpegQuality: # optional, default is 85
    # Use progressive (interlaced) scan for JPEG
    jpegProgressive: # optional, default is false
    # PNG quality level
    pngQuality: # optional, default is 80
    # WEBP quality level
    webpQuality: # optional, default is 85
    # AVIF quality level
    avifQuality: # optional, default is 75
    # Paths to ignore during search
    ignorePaths: # optional, default is node_modules/**
    # Images will be compressed. No commit, or comments will be added to your Pull Request
    compressOnly: # optional, default is false
    # Minimun bytes reduction to be committed
    minAbsChange: # optional, default is 1024
    # Minimun percentage reduction to be committed
    minPctChange: # optional, default is 5

- - name: Frogo-Loading-Indicator-View
  # You may pin to the exact commit or the version.
  # uses: frogobox/frogo-loading-indicator-view@5f3f281cfa93814473778f5ef78157d5b1d05883
  uses: frogobox/frogo-loading-indicator-view@0.0.1-beta01
  with:
    # Input to use
    myInput: # optional, default is world

