- name: Multi-output Example Action
  # You may pin to the exact commit or the version.
  # uses: Ompragash/maths-action@ce21f97ec3f77908d100f117062df204d5cd2555
  uses: Ompragash/maths-action@v1.0.0
  with:
    # First input value
    input1: # default is 10
    # Second input value
    input2: # default is 20
